% Works based off the moves.txt generated by the random movement code
% Takes in 2 files, one has the emg data, one has the moveset.
% Adjusts the emg data to get rid of any early data and data after 300
% seconds.
% Adds the move for each part of the data and then saves it back into a
% csv file.

clear all

fileName1 = '4_1-30.csv';   %Change to correct filenames
fileName2 = 'ArmList.txt';
resultFileName = '4_1-30_labelled.csv';

%Deleting any data before it starts
T = readtable(fileName1,'PreserveVariableNames',true);
while(T{1,1} > 60000 || T{1,1} < 50000)
    disp(T{1,1});
    T(1,:) = [ ];
end

%Deleting any data after 300 seconds
delete  = [];
firstValue = T{1,1};
for j=1:size(T,1)
    if(T{j,1} > (firstValue + 290*10^6) )
        delete = [delete j];
    end
end

T(delete,:) = [];

%Taking the moveset and seperating it into only the move number
moveInput = readtable(fileName2);
moveList = cellfun (@(x) x(1),moveInput(:,2).(1),'un',0);

%Adding the relevant move number for each part of the data
index =[];
count = 1;
for k=1:size(T,1)
    if(T{k,1} > (firstValue + 10^7 * count) )
        count=count+1;
    end
    index = [index; str2num(char(moveList(count)))];
end

T.Label = index;

%Saving it as .csv file
writetable(T,resultFileName);